import React from 'react'
export const countries=[
    'Afghanistan',
    'Albania',
    'Algeria',
    'AmericanSamoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua&Barbuda',
    'Argentina',
    'Armenian',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bonaire',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Canary&Islands',
    'Cape&Verde',
    'Cayman&Islands',
    'Central-African-Republic',
    'Chad',
    'Channel-Islands',
    'Chile',
    'China',
    'Christmas-Island',
    'Cocos-Island',
    'Colombia',
    'Comoros',
    'Congo',
    'Cook-Islands',
    'Costa-Rica',
    'Cote-DIvoire',
    'Croatia',
    'Cuba',
    'Curacao',
    'Cyprus',
    'Czech-Republic',
   ' Denmark',
    'Dominica',
    'Dominican-Republic',
    'Ecuador',
    'Egypt',
    'El-Salvador',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'FaroeIslands',
    'Fiji',
    'Finland',
    'France',
    'FrenchGuiana',
    'FrenchPolynesia',
   
    'Gabon',
    'Gambia',
   'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Great-Britain',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guinea',
    'Guyana',
    'Haiti',
    'Hawaii',
    'Hondura',
    'HongKong',
    'Hungary',
    'Iceland',
    'Indonesia',
    'India',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea-North',
    'Korea-South',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
   'Liechtenstein',
  ' Lithuania',
  ' Luxembourg',
   'Macau',
   'Macedonia',
   'Madagascar',
   'Malaysia',
  ' Malawi',
   'Maldives',
   'Mali',
   'Malta',
   'Martinique',
   'Mauritania',
   'Mauritius',
  
   'Mexico',
   
   'Moldova',
   'Monaco',
   'Mongolia',
   'Montserrat',
   'Morocco',
   'Mozambique',
   'Myanmar',
  ' Nambia',
   'Nauru',
   'Nepal',
   
   'Netherlands',
   
  ' NewZealand',
   'Nicaragua',
   'Niger',
   'Nigeria',
   'Niue',
   'Norway',
   'Oman',
   'Pakistan',
  ' Palestine',
   'Panama',
   'Papua-New-Guinea',
   'Paraguay',
   'Peru',
  ' Philippines',
   
   'Poland',
   'Portugal',
   'PuertoRico',
   'Qatar',
  ' Serbia',
  
   'Romania',
   'Russia',
   'Rwanda',
    
   'Saudi-Arabia',
   'Senegal',
  ' Seychelles',
  
   'Singapore',
   'Slovakia',
   'Slovenia',
   'Somalia',
   'SouthAfrica',
   'Spain',
   'Sri-Lanka',
   'Sudan',
   'Suriname',
   'Swaziland',
   'Sweden',
   'Switzerland',
   'Syria',
   'Taiwan',
   'Tajikistan',
   'Tanzania',
   'Thailand',
  
  
  ' Tunisia',
   'Turkey',
   'Turkmenistan',
   
  ' Uganda',
  ' United-Kingdom',
   'Ukraine',
  ' United-Arab-Emirates',
  ' United_States_of_America',
   'Uruguay',
   'Uzbekistan',
  
   'Vatican',
   'Venezuela',
   'Vietnam',
  
   'Yemen',
   
   'Zambia',
   'Zimbabwe'
]